spring:
  jpa:
    open-in-view: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  task:
    execution:
      pool:
        core-size: 10
        max-size: 10
  datasource:
    password: 1234


server:
  port: 8080
